version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8082:5432"
    networks:
      - app-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Local folder for persistence

  app:
    build: .
    image: springboot-basic
    container_name: springboot-basic-msrv
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local  # Optional: Make sure it's using the local driver
